### ISSUE TITLE
Version 1.1.0 (or maybe 2.0.0) Roadmap.

### ISSUE THREAD

**Issue by zoomlogo** [PyGamer0/flax#67]
- [x] Separate atoms and quicks from `builtins.py`.
- [x] Modify `*_link(` overload atoms.¹
- [x] Add strings.
- [x] Remove the `c` flag.
- [ ] Add string specific overloads.
- [x] Add combinations with replacement.
- [ ] Add more math related stuff. (maybe trigraphs?)
- [ ] https://github.com/zoomlogo/flax/issues/68
- [ ] https://github.com/zoomlogo/flax/issues/69
- [ ] https://github.com/zoomlogo/flax/issues/64 ²

¹ Modify `monadic_link` and `dyadic_link` to accept `overloads=fdict` where fdict is like:
  ```
  {
    "num-num": lambda w,x: w+x,
    "str-lst": ...,
    "str-any": ...,
    "num-any": ...,
    "any-any": ...,
  }
  ```

² For this I will use my own implementation (which I might copy mostly from Vyxal).
